const propertyData =  [
  {
    "bathrooms": 3,
    "bedrooms": 3,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Rent",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/46a28f639826422ad2fc7e2a22695337-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.811703,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2094,
    "longitude": -95.40236,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 1563.804,
    "price": 439900,
    "priceForHDP": 439900,
    "rentZestimate": 2999,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "318 W 28th St",
    "taxAssessedValue": 431449,
    "zestimate": 440500,
    "zipcode": "77008",
    "zpid": 80595095
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Canada",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "MULTI_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/504f1109f98214c54aceea49b95a2c0c-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.912146,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1260,
    "longitude": -95.43812,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 3541.428,
    "price": 174900,
    "priceForHDP": 174900,
    "rentZestimate": 1599,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "10068 Sharpton Dr",
    "taxAssessedValue": 100000,
    "zestimate": 164800,
    "zipcode": "77038",
    "zpid": 28412118
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": -1,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/24c5a8f4e71aa5a3048886648de24b83-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.66023,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1280,
    "longitude": -95.57731,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5000.688,
    "price": 230000,
    "priceForHDP": 230000,
    "rentZestimate": 1650,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "11211 Windmark Dr",
    "taxAssessedValue": 149704,
    "zestimate": 229500,
    "zipcode": "77099",
    "zpid": 28313609
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "datePriceChanged": 1692342000000,
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/f8dbbd7a6a57977e468fd718cc63940d-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.828348,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2570,
    "longitude": -95.538414,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 2509.056,
    "price": 499900,
    "priceChange": -50099,
    "priceForHDP": 499900,
    "priceReduction": "$50,099 (Aug 18)",
    "rentZestimate": 3200,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "9923 Granary Mill Pl",
    "taxAssessedValue": 429350,
    "zestimate": 483000,
    "zipcode": "77080",
    "zpid": 338048455
  },
  {
    "bathrooms": 0,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/e7ffdab00f35f054365092cf8ea614e7-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.651918,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.30059,
    "lotAreaUnit": "acres",
    "lotAreaValue": 0.6152,
    "price": 190000,
    "priceForHDP": 190000,
    "rentZestimate": 1800,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "7109 Fauna St",
    "taxAssessedValue": 217574,
    "zestimate": 243700,
    "zipcode": "77061",
    "zpid": 27840711
  },
  {
    "bathrooms": 2,
    "bedrooms": 4,
    "city": "Canada",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/765a57de7dd688e90da3c21a32a1877a-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.860691,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1724,
    "longitude": -95.209236,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6333.624,
    "price": 254900,
    "priceForHDP": 254900,
    "rentZestimate": 1825,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "9610 Briartrace Ct",
    "taxAssessedValue": 227067,
    "zipcode": "77044",
    "zpid": 126254076
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/d51d3458528f98d0fc9fb7bd7fd54abd-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.782412,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1634,
    "longitude": -95.59164,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 7479.252,
    "price": 460000,
    "priceForHDP": 460000,
    "rentZestimate": 2100,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "14022 Britoak Ln",
    "taxAssessedValue": 388620,
    "zestimate": 462000,
    "zipcode": "77079",
    "zpid": 28113449
  },
  {
    "bathrooms": 3,
    "bedrooms": 3,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": -1,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/ca60f4dd5edc99c5fdb9d6a9e2adc039-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.682568,
    "listing_sub_type": {
      "is_FSBA": true,
      "is_openHouse": true
    },
    "livingArea": 1600,
    "longitude": -95.39944,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 1816.452,
    "openHouse": "Sun. 1-3pm",
    "open_house_info": {
      "open_house_showing": [
        {
          "open_house_end": 1696802400000,
          "open_house_start": 1696795200000
        }
      ]
    },
    "price": 2600,
    "priceForHDP": 2600,
    "rentZestimate": 2350,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2105 Naomi St UNIT A",
    "taxAssessedValue": 306957,
    "unit": "Unit A",
    "zestimate": 342800,
    "zipcode": "77054",
    "zpid": 305255896
  },
  {
    "bathrooms": 0,
    "city": "Kingwood",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/a74a50fdab63cd9d3ecc8b751f48a5cf-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.729424,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.359276,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 2644.092,
    "price": 119000,
    "priceForHDP": 119000,
    "rentZestimate": 1275,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "3313 Sauer St",
    "taxAssessedValue": 78004,
    "zipcode": "77004",
    "zpid": 52400317
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/2a012abbec9e661bc4a465c965cc1bb7-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.967474,
    "listing_sub_type": {
      "is_newHome": true
    },
    "livingArea": 1930,
    "longitude": -95.46529,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 4273.236,
    "newConstructionType": "BUILDER_SPEC",
    "price": 309950,
    "priceForHDP": 309950,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2826 Pine Estate Ln",
    "zipcode": "77014",
    "zpid": 2055134706
  },
  {
    "bathrooms": 1,
    "bedrooms": 1,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "CONDO",
    "imgSrc": "https://photos.zillowstatic.com/fp/8b68d9f6c9127024339abc38a980b9e6-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.725998,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 825,
    "longitude": -95.56604,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6194,
    "price": 139000,
    "priceForHDP": 139000,
    "rentZestimate": 1189,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "10811 Richmond Ave APT 61",
    "taxAssessedValue": 87521,
    "unit": "Apt 61",
    "zestimate": 138100,
    "zipcode": "77042",
    "zpid": 28404456
  },
  {
    "bathrooms": 3,
    "bedrooms": 2,
    "city": "Kingwood",
    "country": "USA",
    "currency": "USD",
    "datePriceChanged": 1696402800000,
    "daysOnZillow": -1,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "CONDO",
    "imgSrc": "https://photos.zillowstatic.com/fp/a731217d3ffc21c0c58df1532d1ceea3-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.76248,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 3992,
    "longitude": -95.46525,
    "price": 645000,
    "priceChange": -5000,
    "priceForHDP": 645000,
    "priceReduction": "$5,000 (Oct 4)",
    "rentZestimate": 4158,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5050 Woodway Dr APT 8P",
    "taxAssessedValue": 541000,
    "unit": "Apt 8P",
    "zipcode": "77056",
    "zpid": 161266549
  },
  {
    "bathrooms": 3,
    "bedrooms": 6,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/adde45a377ad8f11feb5ad03156a1512-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.537918,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 3284,
    "longitude": -95.09157,
    "lotAreaUnit": "acres",
    "lotAreaValue": 0.2978,
    "price": 620000,
    "priceForHDP": 620000,
    "rentZestimate": 2800,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "18614 Carriage Ct",
    "taxAssessedValue": 383630,
    "zestimate": 618300,
    "zipcode": "77058",
    "zpid": 28096639
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/9b6d1c391dda086a70328c2073caced8-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.942144,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 3000,
    "longitude": -95.58571,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 7623,
    "price": 398000,
    "priceForHDP": 398000,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "11014 Forrest Valley Dr",
    "zipcode": "77065",
    "zpid": 2055135460
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Kingwood",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/bcbef39b5aec8b5f5e7d97b43dab3def-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.644575,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2024,
    "longitude": -95.54581,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 8398.368,
    "price": 299000,
    "priceForHDP": 299000,
    "rentZestimate": 1999,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "12403 Millbanks Dr",
    "taxAssessedValue": 235950,
    "zestimate": 298500,
    "zipcode": "77031",
    "zpid": 28176836
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "datePriceChanged": 1696402800000,
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/903b1acf7aaa6bd752f7d1db349e7e67-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.923288,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2948,
    "longitude": -95.63514,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 7775.46,
    "price": 358000,
    "priceChange": -11950,
    "priceForHDP": 358000,
    "priceReduction": "$11,950 (Oct 4)",
    "rentZestimate": 2849,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "10154 Twila Springs Ct",
    "taxAssessedValue": 320154,
    "zestimate": 358000,
    "zipcode": "77095",
    "zpid": 80584066
  },
  {
    "bathrooms": 0,
    "city": "Kingwood",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/42645a29ae706be3ca9717b7b97207ee-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.688519,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.37092,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5000.688,
    "price": 126000,
    "priceForHDP": 126000,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "3557 Corder St",
    "zipcode": "77021",
    "zpid": 2055136027
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "MULTI_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/d4b6e71105ffa6e7a6326dda324e85a9-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.810314,
    "listing_sub_type": {
      "is_newHome": true
    },
    "livingArea": 1960,
    "longitude": -95.27947,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5000,
    "newConstructionType": "NEW_CONSTRUCTION_TYPE_OTHER",
    "price": 248990,
    "priceForHDP": 248990,
    "rentZestimate": 1700,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5409 Nielan St",
    "taxAssessedValue": 42750,
    "zipcode": "77028",
    "zpid": 97657405
  },
  {
    "bathrooms": 0,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/b845745eb02a2c79f6ff34c266f80da6-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.700129,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.356804,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 7801.596,
    "price": 258400,
    "priceForHDP": 258400,
    "rentZestimate": 1700,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "6102 Sherwood Dr",
    "taxAssessedValue": 89600,
    "zestimate": 133300,
    "zipcode": "77021",
    "zpid": 27935632
  },
  {
    "bathrooms": 2,
    "bedrooms": 2,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/8f431efae4b4e825fabb4c3a6007243b-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.825232,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 952,
    "longitude": -95.37121,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5998.212,
    "price": 185000,
    "priceForHDP": 185000,
    "rentZestimate": 1297,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "7114 Bauman Rd",
    "taxAssessedValue": 117723,
    "zestimate": 184300,
    "zipcode": "77022",
    "zpid": 27811430
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Canada",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/7abb4772f779bb0d60be59a2b38f2d4f-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.83663,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1459,
    "longitude": -95.45022,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 8102.16,
    "price": 399900,
    "priceForHDP": 399900,
    "rentZestimate": 2498,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2102 Latexo Dr",
    "taxAssessedValue": 380522,
    "zestimate": 400000,
    "zipcode": "77018",
    "zpid": 28016781
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/a442f56832bad058764d3a31a760260a-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.846231,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1696,
    "longitude": -95.47584,
    "lotAreaUnit": "acres",
    "lotAreaValue": 0.2569,
    "price": 319900,
    "priceForHDP": 319900,
    "rentZestimate": 1849,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5822 Silver Forest Dr",
    "taxAssessedValue": 331608,
    "zestimate": 319000,
    "zipcode": "77092",
    "zpid": 28096031
  },
  {
    "bathrooms": 0,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/7e46cc246ea27f28170945110b0ca7c9-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.858414,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.31046,
    "lotAreaUnit": "acres",
    "lotAreaValue": 1.5077,
    "price": 260000,
    "priceForHDP": 260000,
    "rentZestimate": 1900,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5402 Styling Dr",
    "taxAssessedValue": 78020,
    "zestimate": 176700,
    "zipcode": "77016",
    "zpid": 97634951
  },
  {
    "bathrooms": 3,
    "bedrooms": 3,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/816e896179b8366133656fabbaae7a06-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.86507,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2670,
    "longitude": -95.59796,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6900,
    "price": 408000,
    "priceForHDP": 408000,
    "rentZestimate": 2400,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "12619 Tallwood Crossing Ln",
    "taxAssessedValue": 313000,
    "zestimate": 407800,
    "zipcode": "77041",
    "zpid": 58675636
  },
  {
    "bathrooms": 4,
    "bedrooms": 4,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/3a193bcb1cc299a52b70f2b8c25ab226-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.741022,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 3848,
    "longitude": -95.398346,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6250.86,
    "price": 1899000,
    "priceForHDP": 1899000,
    "rentZestimate": 11880,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "1521 Harold St",
    "taxAssessedValue": 1605897,
    "zestimate": 1891100,
    "zipcode": "77006",
    "zpid": 27815648
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/a848d9dc330159c5fd35f019d56e3f81-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.984749,
    "listing_sub_type": {
      "is_FSBA": true
    },
    
    "livingArea": 2712,
    "longitude": -95.510376,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 9239.076,
    "price": 272000,
    "priceForHDP": 272000,
    "rentZestimate": 2496,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "13310 Glen Erica Dr",
    "taxAssessedValue": 284876,
    "zestimate": 272200,
    "zipcode": "77069",
    "zpid": 28138835
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "datePriceChanged": 1692342000000,
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/f8dbbd7a6a57977e468fd718cc63940d-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.828348,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2570,
    "longitude": -95.538414,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 2509.056,
    "price": 499900,
    "priceChange": -50099,
    "priceForHDP": 499900,
    "priceReduction": "$50,099 (Aug 18)",
    "rentZestimate": 3200,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "9923 Granary Mill Pl",
    "taxAssessedValue": 429350,
    "zestimate": 483000,
    "zipcode": "77080",
    "zpid": 338048455
  },
  {
    "bathrooms": 0,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/e7ffdab00f35f054365092cf8ea614e7-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.651918,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.30059,
    "lotAreaUnit": "acres",
    "lotAreaValue": 0.6152,
    "price": 190000,
    "priceForHDP": 190000,
    "rentZestimate": 1800,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "7109 Fauna St",
    "taxAssessedValue": 217574,
    "zestimate": 243700,
    "zipcode": "77061",
    "zpid": 27840711
  },
  {
    "bathrooms": 2,
    "bedrooms": 4,
    "city": "Canada",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/765a57de7dd688e90da3c21a32a1877a-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.860691,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1724,
    "longitude": -95.209236,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6333.624,
    "price": 254900,
    "priceForHDP": 254900,
    "rentZestimate": 1825,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "9610 Briartrace Ct",
    "taxAssessedValue": 227067,
    "zipcode": "77044",
    "zpid": 126254076
  },
  {
    "bathrooms": 2,
    "bedrooms": 2,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "CONDO",
    "imgSrc": "https://photos.zillowstatic.com/fp/32718001ee44273f524cca42b5af26f2-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.703178,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1386,
    "longitude": -95.42091,
    "lotAreaUnit": "acres",
    "lotAreaValue": 1.8291,
    "price": 159900,
    "priceForHDP": 159900,
    "rentZestimate": 2496,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2700 Bellefontaine St APT B1",
    "taxAssessedValue": 125790,
    "unit": "Apt B1",
    "zestimate": 158400,
    "zipcode": "77025",
    "zpid": 28298119
  },
  {
    "bathrooms": 2,
    "bedrooms": 2,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "datePriceChanged": 1696316400000,
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "CONDO",
    "imgSrc": "https://photos.zillowstatic.com/fp/b0a3354dda8ce78ed9ddfc856bb91e15-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.735739,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1370,
    "longitude": -95.46521,
    "price": 239000,
    "priceChange": -10000,
    "priceForHDP": 239000,
    "priceReduction": "$10,000 (Oct 3)",
    "rentZestimate": 2609,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5150 Hidalgo St UNIT 1203",
    "taxAssessedValue": 193913,
    "unit": "Unit 1203",
    "zipcode": "77056",
    "zpid": 28420283
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/2a19394d17b93bc36f1163ae78a59f6c-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.718357,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2072,
    "longitude": -95.37108,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5610.528,
    "price": 574990,
    "priceForHDP": 574990,
    "rentZestimate": 2450,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2906 Southmore Blvd",
    "taxAssessedValue": 289101,
    "zestimate": 571700,
    "zipcode": "77004",
    "zpid": 27848616
  },
  {
    "bathrooms": 4,
    "bedrooms": 3,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": -1,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "TOWNHOUSE",
    "imgSrc": "https://photos.zillowstatic.com/fp/374e03695a4c115699fda5931b7f63b1-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.799072,
    "listing_sub_type": {
      "is_FSBA": true,
      "is_openHouse": true
    },
    "livingArea": 2099,
    "longitude": -95.420074,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 1815,
    "openHouse": "Sat. 2-4pm",
    "open_house_info": {
      "open_house_showing": [
        {
          "open_house_end": 1696719600000,
          "open_house_start": 1696712400000
        },
        {
          "open_house_end": 1696806000000,
          "open_house_start": 1696798800000
        }
      ]
    },
    "price": 419500,
    "priceForHDP": 419500,
    "rentZestimate": 2949,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "1129 W 15th 1/2 St UNIT A",
    "taxAssessedValue": 352267,
    "unit": "Unit A",
    "zestimate": 420100,
    "zipcode": "77008",
    "zpid": 80597341
  },
  {
    "bathrooms": 3,
    "bedrooms": 3,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/65145450c714b7a82071020f493d656d-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.635365,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2120,
    "longitude": -95.46744,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 4887.432,
    "price": 300000,
    "priceForHDP": 300000,
    "rentZestimate": 1999,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5603 Tiger Lilly Way",
    "taxAssessedValue": 266435,
    "zestimate": 299700,
    "zipcode": "77085",
    "zpid": 63348692
  },
  {
    "bathrooms": 4,
    "bedrooms": 5,
    "city": "Kingwood",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/28e9b8afe000e929b9323fee0ca8fbee-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 30.046295,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 4186,
    "longitude": -95.16771,
    "lotAreaUnit": "acres",
    "lotAreaValue": 0.6357,
    "price": 675000,
    "priceForHDP": 675000,
    "rentZestimate": 4512,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2202 Sunshine Point Dr",
    "taxAssessedValue": 645073,
    "zestimate": 674300,
    "zipcode": "77345",
    "zpid": 28426503
  },
  {
    "bathrooms": 0,
    "city": "Kingwood",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/42645a29ae706be3ca9717b7b97207ee-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.688519,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.37092,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5000.688,
    "price": 126000,
    "priceForHDP": 126000,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "3557 Corder St",
    "zipcode": "77021",
    "zpid": 2055136027
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Rent",
    "homeStatusForHDP": "For Sale",
    "homeType": "MULTI_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/d4b6e71105ffa6e7a6326dda324e85a9-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.810314,
    "listing_sub_type": {
      "is_newHome": true
    },
    "livingArea": 1960,
    "longitude": -95.27947,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5000,
    "newConstructionType": "NEW_CONSTRUCTION_TYPE_OTHER",
    "price": 248990,
    "priceForHDP": 248990,
    "rentZestimate": 1700,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5409 Nielan St",
    "taxAssessedValue": 42750,
    "zipcode": "77028",
    "zpid": 97657405
  },
  {
    "bathrooms": 4,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "TOWNHOUSE",
    "imgSrc": "https://photos.zillowstatic.com/fp/a6b7b02a0afbad3efede79728aa5629f-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.765545,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2109,
    "longitude": -95.40276,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 1921,
    "price": 535000,
    "priceForHDP": 535000,
    "rentZestimate": 3200,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "4208 Dickson St",
    "taxAssessedValue": 479905,
    "zestimate": 534800,
    "zipcode": "77007",
    "zpid": 118400542
  },
  {
    "bathrooms": 1,
    "bedrooms": 3,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": -1,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/e0262febc6f8a844cef18bafa0e61ee0-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.690899,
    "listing_sub_type": {
      "is_FSBA": true,
      "is_openHouse": true
    },
    "livingArea": 941,
    "longitude": -95.34487,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6599.34,
    "openHouse": "Sat. 3-5pm",
    "open_house_info": {
      "open_house_showing": [
        {
          "open_house_end": 1696723200000,
          "open_house_start": 1696716000000
        }
      ]
    },
    "price": 110000,
    "priceForHDP": 110000,
    "rentZestimate": 1299,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "4926 Kelso St",
    "taxAssessedValue": 112663,
    "zestimate": 107600,
    "zipcode": "77021",
    "zpid": 27951708
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "datePriceChanged": 1696316400000,
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/529fa109e9d83f2e4d1fc74272af477f-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.977903,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2340,
    "longitude": -95.50857,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 9361.044,
    "price": 279000,
    "priceChange": -8500,
    "priceForHDP": 279000,
    "priceReduction": "$8,500 (Oct 3)",
    "rentZestimate": 2299,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "12703 Rocky Hill Dr",
    "taxAssessedValue": 266540,
    "zestimate": 278900,
    "zipcode": "77066",
    "zpid": 28150516
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/e3f877592876d5d73c1f1dfb8c8603b4-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.993473,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1639,
    "longitude": -95.59744,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 9471,
    "price": 239990,
    "priceForHDP": 239990,
    "rentZestimate": 1800,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "15102 Rolling Oaks Dr",
    "taxAssessedValue": 227580,
    "zestimate": 239900,
    "zipcode": "77070",
    "zpid": 28275388
  },
  {
    "bathrooms": 1,
    "bedrooms": 1,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "CONDO",
    "imgSrc": "https://photos.zillowstatic.com/fp/d283a0ca729e0c505145150490f339a6-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.746634,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1044,
    "longitude": -95.43712,
    "price": 399000,
    "priceForHDP": 399000,
    "rentZestimate": 2708,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "3711 San Felipe St UNIT 4I",
    "taxAssessedValue": 277332,
    "unit": "Unit 4I",
    "zestimate": 306200,
    "zipcode": "77027",
    "zpid": 28301843
  },
  {
    "bathrooms": 4,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": -1,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/d4565058b252a273fa99b283e57bcf6c-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.767893,
    "listing_sub_type": {
      "is_FSBA": true,
      "is_openHouse": true
    },
    "livingArea": 3602,
    "longitude": -95.47504,
    "lotAreaUnit": "acres",
    "lotAreaValue": 0.3558,
    "openHouse": "Thu. 11:30am-2pm",
    "open_house_info": {
      "open_house_showing": [
        {
          "open_house_end": 1696539600000,
          "open_house_start": 1696530600000
        },
        {
          "open_house_end": 1696806000000,
          "open_house_start": 1696798800000
        }
      ]
    },
    "price": 1650000,
    "priceForHDP": 1650000,
    "rentZestimate": 9311,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "267 Maple Valley Rd",
    "taxAssessedValue": 1398738,
    "zestimate": 1643200,
    "zipcode": "77056",
    "zpid": 28001476
  },
  {
    "bathrooms": 2,
    "bedrooms": 2,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "datePriceChanged": 1696316400000,
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "CONDO",
    "imgSrc": "https://photos.zillowstatic.com/fp/b0a3354dda8ce78ed9ddfc856bb91e15-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.735739,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1370,
    "longitude": -95.46521,
    "price": 239000,
    "priceChange": -10000,
    "priceForHDP": 239000,
    "priceReduction": "$10,000 (Oct 3)",
    "rentZestimate": 2609,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5150 Hidalgo St UNIT 1203",
    "taxAssessedValue": 193913,
    "unit": "Unit 1203",
    "zipcode": "77056",
    "zpid": 28420283
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/2a19394d17b93bc36f1163ae78a59f6c-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.718357,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2072,
    "longitude": -95.37108,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5610.528,
    "price": 574990,
    "priceForHDP": 574990,
    "rentZestimate": 2450,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2906 Southmore Blvd",
    "taxAssessedValue": 289101,
    "zestimate": 571700,
    "zipcode": "77004",
    "zpid": 27848616
  },
  {
    "bathrooms": 4,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "TOWNHOUSE",
    "imgSrc": "https://photos.zillowstatic.com/fp/a6b7b02a0afbad3efede79728aa5629f-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.765545,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2109,
    "longitude": -95.40276,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 1921,
    "price": 535000,
    "priceForHDP": 535000,
    "rentZestimate": 3200,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "4208 Dickson St",
    "taxAssessedValue": 479905,
    "zestimate": 534800,
    "zipcode": "77007",
    "zpid": 118400542
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/a442f56832bad058764d3a31a760260a-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.846231,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1696,
    "longitude": -95.47584,
    "lotAreaUnit": "acres",
    "lotAreaValue": 0.2569,
    "price": 319900,
    "priceForHDP": 319900,
    "rentZestimate": 1849,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5822 Silver Forest Dr",
    "taxAssessedValue": 331608,
    "zestimate": 319000,
    "zipcode": "77092",
    "zpid": 28096031
  },
  {
    "bathrooms": 0,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/7e46cc246ea27f28170945110b0ca7c9-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.858414,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.31046,
    "lotAreaUnit": "acres",
    "lotAreaValue": 1.5077,
    "price": 260000,
    "priceForHDP": 260000,
    "rentZestimate": 1900,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5402 Styling Dr",
    "taxAssessedValue": 78020,
    "zestimate": 176700,
    "zipcode": "77016",
    "zpid": 97634951
  },
  {
    "bathrooms": 3,
    "bedrooms": 3,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/816e896179b8366133656fabbaae7a06-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.86507,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2670,
    "longitude": -95.59796,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6900,
    "price": 408000,
    "priceForHDP": 408000,
    "rentZestimate": 2400,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "12619 Tallwood Crossing Ln",
    "taxAssessedValue": 313000,
    "zestimate": 407800,
    "zipcode": "77041",
    "zpid": 58675636
  },
  {
    "bathrooms": 4,
    "bedrooms": 4,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/3a193bcb1cc299a52b70f2b8c25ab226-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.741022,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 3848,
    "longitude": -95.398346,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6250.86,
    "price": 1899000,
    "priceForHDP": 1899000,
    "rentZestimate": 11880,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "1521 Harold St",
    "taxAssessedValue": 1605897,
    "zestimate": 1891100,
    "zipcode": "77006",
    "zpid": 27815648
  },
  {
    "bathrooms": 1,
    "bedrooms": 3,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": -1,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/e0262febc6f8a844cef18bafa0e61ee0-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.690899,
    "listing_sub_type": {
      "is_FSBA": true,
      "is_openHouse": true
    },
    "livingArea": 941,
    "longitude": -95.34487,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 6599.34,
    "openHouse": "Sat. 3-5pm",
    "open_house_info": {
      "open_house_showing": [
        {
          "open_house_end": 1696723200000,
          "open_house_start": 1696716000000
        }
      ]
    },
    "price": 110000,
    "priceForHDP": 110000,
    "rentZestimate": 1299,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "4926 Kelso St",
    "taxAssessedValue": 112663,
    "zestimate": 107600,
    "zipcode": "77021",
    "zpid": 27951708
  },
  {
    "bathrooms": 0,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "LOT",
    "imgSrc": "https://photos.zillowstatic.com/fp/da89c5f535dc14aedff92178e8d18ca2-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.944183,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "longitude": -95.55227,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 10497.96,
    "price": 469000,
    "priceForHDP": 469000,
    "rentZestimate": 1450,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "11803 Beeville Dr",
    "zestimate": 474500,
    "zipcode": "77064",
    "zpid": 2062575423
  },
  {
    "bathrooms": 2,
    "bedrooms": 3,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/e3f877592876d5d73c1f1dfb8c8603b4-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.993473,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1639,
    "longitude": -95.59744,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 9471,
    "price": 239990,
    "priceForHDP": 239990,
    "rentZestimate": 1800,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "15102 Rolling Oaks Dr",
    "taxAssessedValue": 227580,
    "zestimate": 239900,
    "zipcode": "77070",
    "zpid": 28275388
  },
  {
    "bathrooms": 4,
    "bedrooms": 3,
    "city": "Alaska",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": -1,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "TOWNHOUSE",
    "imgSrc": "https://photos.zillowstatic.com/fp/374e03695a4c115699fda5931b7f63b1-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.799072,
    "listing_sub_type": {
      "is_FSBA": true,
      "is_openHouse": true
    },
    "livingArea": 2099,
    "longitude": -95.420074,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 1815,
    "openHouse": "Sat. 2-4pm",
    "open_house_info": {
      "open_house_showing": [
        {
          "open_house_end": 1696719600000,
          "open_house_start": 1696712400000
        },
        {
          "open_house_end": 1696806000000,
          "open_house_start": 1696798800000
        }
      ]
    },
    "price": 419500,
    "priceForHDP": 419500,
    "rentZestimate": 2949,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "1129 W 15th 1/2 St UNIT A",
    "taxAssessedValue": 352267,
    "unit": "Unit A",
    "zestimate": 420100,
    "zipcode": "77008",
    "zpid": 80597341
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/a848d9dc330159c5fd35f019d56e3f81-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.984749,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2712,
    "longitude": -95.510376,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 9239.076,
    "price": 272000,
    "priceForHDP": 272000,
    "rentZestimate": 2496,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "13310 Glen Erica Dr",
    "taxAssessedValue": 284876,
    "zestimate": 272200,
    "zipcode": "77069",
    "zpid": 28138835
  },
  {
    "bathrooms": 2,
    "bedrooms": 2,
    "city": "California",
    "country": "USA",
    "currency": "USD",
    "datePriceChanged": 1696316400000,
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "CONDO",
    "imgSrc": "https://photos.zillowstatic.com/fp/b0a3354dda8ce78ed9ddfc856bb91e15-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.735739,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1370,
    "longitude": -95.46521,
    "price": 239000,
    "priceChange": -10000,
    "priceForHDP": 239000,
    "priceReduction": "$10,000 (Oct 3)",
    "rentZestimate": 2609,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "5150 Hidalgo St UNIT 1203",
    "taxAssessedValue": 193913,
    "unit": "Unit 1203",
    "zipcode": "77056",
    "zpid": 28420283
  },
  {
    "bathrooms": 3,
    "bedrooms": 4,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "SINGLE_FAMILY",
    "imgSrc": "https://photos.zillowstatic.com/fp/2a19394d17b93bc36f1163ae78a59f6c-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.718357,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 2072,
    "longitude": -95.37108,
    "lotAreaUnit": "sqft",
    "lotAreaValue": 5610.528,
    "price": 574990,
    "priceForHDP": 574990,
    "rentZestimate": 2450,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2906 Southmore Blvd",
    "taxAssessedValue": 289101,
    "zestimate": 571700,
    "zipcode": "77004",
    "zpid": 27848616
  },
  {
    "bathrooms": 2,
    "bedrooms": 2,
    "city": "Houston",
    "country": "USA",
    "currency": "USD",
    "daysOnZillow": 0,
    "homeStatus": "For Sale",
    "homeStatusForHDP": "For Sale",
    "homeType": "CONDO",
    "imgSrc": "https://photos.zillowstatic.com/fp/32718001ee44273f524cca42b5af26f2-p_e.jpg",
    "isFeatured": false,
    "isNonOwnerOccupied": true,
    "isPreforeclosureAuction": false,
    "isPremierBuilder": false,
    "isShowcaseListing": false,
    "isUnmappable": false,
    "isZillowOwned": false,
    "latitude": 29.703178,
    "listing_sub_type": {
      "is_FSBA": true
    },
    "livingArea": 1386,
    "longitude": -95.42091,
    "lotAreaUnit": "acres",
    "lotAreaValue": 1.8291,
    "price": 159900,
    "priceForHDP": 159900,
    "rentZestimate": 2496,
    "shouldHighlight": false,
    "state": "TX",
    "streetAddress": "2700 Bellefontaine St APT B1",
    "taxAssessedValue": 125790,
    "unit": "Apt B1",
    "zestimate": 158400,
    "zipcode": "77025",
    "zpid": 28298119
  },
]


export default propertyData;